export const LoginUrl = '/login';
export const isLoginUrl = '/is-login';
export const isLdapLoginUrl = '/ldap/login'; // LDAP登录认证
export const LogoutUrl = '/signout';
export const GetMenuListUrl = '/api/user/menu';
export const GetPublicKeyUrl = '/get-key';
export const UpdateLocalConfigUrl = '/user/local/config/update'; // 个人设置-更新本地执行配置
export const AddLocalConfigUrl = '/user/local/config/add'; // 个人设置-添加本地执行
export const ValidLocalConfigUrl = '/user/local/config/validate'; // 个人设置-验证本地执行
export const GetLocalConfigUrl = '/user/local/config/get'; // 个人设置-获取本地执行配置
export const EnableLocalConfigUrl = '/user/local/config/enable'; // 个人设置-启用本地执行配置
export const DisableLocalConfigUrl = '/user/local/config/disable'; // 个人设置-禁用本地执行配置
export const UpdateAPIKEYUrl = '/user/api/key/update'; // 个人设置-更新 APIKEY
export const ValidAPIKEYUrl = '/user/api/key/validate'; // 个人设置-验证 APIKEY
export const GetAPIKEYListUrl = '/user/api/key/list'; // 个人设置-获取 APIKEY 列表
export const EnableAPIKEYUrl = '/user/api/key/enable'; // 个人设置-开启 APIKEY
export const DisableAPIKEYUrl = '/user/api/key/disable'; // 个人设置-关闭 APIKEY
export const DeleteAPIKEYUrl = '/user/api/key/delete'; // 个人设置-删除 APIKEY
export const AddAPIKEYUrl = '/user/api/key/add'; // 个人设置-生成 APIKEY
export const UpdatePswUrl = '/personal/update-password'; // 个人信息-修改密码
export const UpdateInfoUrl = '/personal/update-info'; // 个人信息-修改信息
export const GetInfoUrl = '/personal/get'; // 个人信息-获取信息
export const ValidatePlatformUrl = '/user/platform/validate'; // 个人信息-校验服务集成信息
export const SavePlatformUrl = '/user/platform/save'; // 个人信息-保存三方平台账号信息
export const GetPlatformUrl = '/user/platform/get'; // 个人信息-获取三方平台账号信息
export const GetPlatformAccountUrl = '/user/platform/account/info'; // 个人信息-获取三方平台账号信息-插件信息
