export const LoginUrl = '/login';
export const isLoginUrl = '/is-login';
export const ldapLoginUrl = '/ldap/login'; // LDAP登录认证
export const getAuthenticationUrl = '/authentication/get-list'; // 获取登录方式
export const LogoutUrl = '/signout';
export const GetMenuListUrl = '/api/user/menu';
export const GetPublicKeyUrl = '/get-key';
export const UpdateLocalConfigUrl = '/user/local/config/update'; // 个人设置-更新本地执行配置
export const AddLocalConfigUrl = '/user/local/config/add'; // 个人设置-添加本地执行
export const ValidLocalConfigUrl = '/status'; // 个人设置-验证本地执行
export const GetLocalConfigUrl = '/user/local/config/get'; // 个人设置-获取本地执行配置
export const EnableLocalConfigUrl = '/user/local/config/enable'; // 个人设置-启用本地执行配置
export const DisableLocalConfigUrl = '/user/local/config/disable'; // 个人设置-禁用本地执行配置
export const UpdateAPIKEYUrl = '/user/api/key/update'; // 个人设置-更新 APIKEY
export const ValidAPIKEYUrl = '/user/api/key/validate'; // 个人设置-验证 APIKEY
export const GetAPIKEYListUrl = '/user/api/key/list'; // 个人设置-获取 APIKEY 列表
export const EnableAPIKEYUrl = '/user/api/key/enable'; // 个人设置-开启 APIKEY
export const DisableAPIKEYUrl = '/user/api/key/disable'; // 个人设置-关闭 APIKEY
export const DeleteAPIKEYUrl = '/user/api/key/delete'; // 个人设置-删除 APIKEY
export const AddAPIKEYUrl = '/user/api/key/add'; // 个人设置-生成 APIKEY
export const UpdatePswUrl = '/personal/update-password'; // 个人信息-修改密码
export const UpdateInfoUrl = '/personal/update-info'; // 个人信息-修改信息
export const UpdateLanguageUrl = '/personal/update-locale'; // 个人信息-修改语言
export const GetInfoUrl = '/personal/get'; // 个人信息-获取信息
export const ValidatePlatformUrl = '/user/platform/validate'; // 个人信息-校验服务集成信息
export const SavePlatformUrl = '/user/platform/save'; // 个人信息-保存三方平台账号信息
export const GetPlatformUrl = '/user/platform/get'; // 个人信息-获取三方平台账号信息
export const GetPlatformAccountUrl = '/user/platform/account/info'; // 个人信息-获取三方平台账号信息-插件信息
export const GetPlatformOrgOptionUrl = '/user/platform/switch-option'; // 个人信息-获取三方平台账号信息-插件信息
export const GetWeComInfoUrl = '/we_com/info'; // 获取企业微信登陆的配置信息
export const GetWeComCallbackUrl = '/sso/callback/we_com'; // 获取企业微信登陆的回调信息
export const GetPlatformParamUrl = '/setting/get/platform/param';
export const GeDingInfoUrl = '/ding_talk/info'; // 获取企业微信登陆的配置信息
export const GetDingCallbackUrl = '/sso/callback/ding_talk'; // 获取企业微信登陆的回调信息
export const GeLarkInfoUrl = '/lark/info'; // 获取飞书登陆的配置信息
export const GetLarkCallbackUrl = '/sso/callback/lark'; // 获取飞书登陆的回调信息
export const GeLarkSuiteInfoUrl = '/lark_suite/info'; // 获取国际飞书登陆的配置信息
export const GetLarkSuiteCallbackUrl = '/sso/callback/lark_suite'; // 获取国际飞书登陆的回调信息
export const GetDefaultLocaleUrl = '/user/local/config/default-locale'; // 获取默认语言配置
// 个人中心-模型配置
export const PersonalModelConfigListUrl = '/personal/model/source/list'; // 查看模型集合
export const PersonalEditModelConfigUrl = '/personal/model/edit-source'; // 编辑模型设置
export const PersonalGetModelConfigDetailUrl = '/personal/model/get'; // 获取模型信息
export const PersonalDeleteModelConfigUrl = '/personal/model/delete'; // 删除模型
