export default {
  id: "API",
  state: () => ({
    projectId: "",
    test: {},
    scenarioJmxs: {},
    versionSwitch: "new",
    isReadOnly: true,
    theme: undefined,
    testCaseSelectNode: {},
    testCasePublicSelectNode: {},
    testCaseSelectNodeIds: [],
    testCaseModuleOptions: [],
    testReviewSelectNode: {},
    testReviewSelectNodeIds: [],
    useEnvironment: "",
    testPlanViewSelectNode: {},
    selectStep: {},
    currentApiCase: {},
    pluginFiles: [],
    isTestCaseMinderChanged: false,
    // 当前项目是否勾选自定义ID
    currentProjectIsCustomNum: false,
    testCaseTemplate: {},
    scenarioEnvMap: new Map(),
    apiMap: new Map(),
    apiStatus: new Map(),
    apiCaseMap: new Map(),
    testCaseMap: new Map(),
    curTabId: null,
    testCaseDefaultValue: {},
    forceRerenderIndex: "",
    currentScenario: {},
    scenarioDefinition: {},
    selectCommand: {},
    //按照type分组的指令
    groupedCmd: {},
    selectUiGroup: '',
    librarySelectElement: {},
    uiElementLibraryModuleIds: null,
    uiElementLibraryElements: null,
    refreshUiScenario: false,
    showLicenseCountWarning: false,
    temWorkspaceId: null,
    fileDownloadList: [], // 文件下载进度列表,
    appFixed: null,
  }),
  persist: true,
  getters: {
    currentApi(store) {
      return store.$state
    },
  },
}
