export enum EnvAuthScopeEnum {
  PROJECT = 'PROJECT',
  PROJECT_GROUP = 'PROJECT_GROUP',
}

export enum EnvAuthTypeEnum {
  GLOBAL = 'GLOBAL', // 全局参数
  ENVIRONMENT = 'ENVIRONMENT', // 环境
  ENVIRONMENT_PARAM = 'ENVIRONMENT_PARAM', // 环境参数
  ENVIRONMENT_GROUP = 'ENVIRONMENT_GROUP', // 环境组
}

// 环境的tab
export enum EnvTabTypeEnum {
  ENVIRONMENT_PARAM = 'ENVIRONMENT_PARAM', // 环境变量
  ENVIRONMENT_HTTP = 'ENVIRONMENT_HTTP', // Http
  ENVIRONMENT_DATABASE = 'ENVIRONMENT_DATABASE', // 数据库
  ENVIRONMENT_HOST = 'ENVIRONMENT_HOST', // 域名
  ENVIRONMENT_PRE = 'ENVIRONMENT_PRE', // 前置
  ENVIRONMENT_POST = 'ENVIRONMENT_POST', // 后置
  ENVIRONMENT_ASSERT = 'ENVIRONMENT_ASSERT', // 断言
  ENVIRONMENT_SETTING = 'SETTING', // 设置
}
