export enum MessageResourceType {
  TEST_PLAN_TASK = 'TEST_PLAN_TASK',
  TEST_PLAN_REPORT_TASK = 'TEST_PLAN_REPORT_TASK',
  BUG_TASK = 'BUG_TASK',
  BUG_SYNC_TASK = 'BUG_SYNC_TASK',
  FUNCTIONAL_CASE_TASK = 'FUNCTIONAL_CASE_TASK',
  CASE_REVIEW_TASK = 'CASE_REVIEW_TASK',
  API_DEFINITION_TASK = 'API_DEFINITION_TASK',
  API_SCENARIO_TASK = 'API_SCENARIO_TASK',
  API_REPORT_TASK = 'API_REPORT_TASK',
  UI_SCENARIO_TASK = 'UI_SCENARIO_TASK',
  UI_REPORT_TASK = 'UI_REPORT_TASK',
  LOAD_TEST_TASK = 'LOAD_TEST_TASK',
  LOAD_REPORT_TASK = 'LOAD_REPORT_TASK',
  SCHEDULE_TASK = 'SCHEDULE_TASK',
  JENKINS_TASK = 'JENKINS_TASK',
}

export default {};
