export const UpdateModuleUrl = '/api/scenario/module/update'; // 更新模块
export const GetModuleTreeUrl = '/api/scenario/module/tree'; // 查找模块
export const MoveModuleUrl = '/api/scenario/module/move'; // 移动模块
export const GetModuleCountUrl = '/api/scenario/module/count'; // 获取模块统计数量
export const AddModuleUrl = '/api/scenario/module/add'; // 添加模块
export const DeleteModuleUrl = '/api/scenario/module/delete'; // 删除模块
// export const GetEnvModuleUrl = '/api/scenario/module/env/tree'; // 获取环境的模块树
// export const DefinitionPageUrl = '/api/scenario/page'; // 接口定义列表
// export const AddDefinitionUrl = '/api/scenario/add'; // 添加接口定义
// export const UpdateDefinitionUrl = '/api/scenario/update'; // 更新接口定义
// export const GetDefinitionDetailUrl = '/api/scenario/get-detail'; // 获取接口定义详情
// export const TransferFileUrl = '/api/scenario/transfer'; // 文件转存
// export const TransferFileModuleOptionUrl = '/api/scenario/transfer/options'; // 文件转存目录
// export const UploadTempFileUrl = '/api/scenario/upload/temp/file'; // 临时文件上传
// export const DefinitionMockPageUrl = '/api/scenario/mock/page'; // mock列表
// export const UpdateMockStatusUrl = '/api/scenario/mock/enable/'; // 更新mock状态
// export const DeleteMockUrl = '/api/scenario/mock/delete'; // 刪除mock
// export const DeleteDefinitionUrl = '/api/scenario/delete-to-gc'; // 删除接口定义
// export const ImportDefinitionUrl = '/api/scenario/import'; // 导入接口定义
// export const SortDefinitionUrl = '/api/scenario/edit/pos'; // 接口定义拖拽
// export const BatchUpdateDefinitionUrl = '/api/scenario/batch-update'; // 批量更新接口定义
// export const BatchMoveDefinitionUrl = '/api/scenario/batch-move'; // 批量移动接口定义
// export const BatchDeleteDefinitionUrl = '/api/scenario/batch/delete-to-gc'; // 批量删除接口定义
// export const UpdateDefinitionScheduleUrl = '/api/scenario/schedule/update'; // 接口定义-定时同步-更新
// export const CheckDefinitionScheduleUrl = '/api/scenario/schedule/check'; // 接口定义-定时同步-检查 url 是否存在
// export const AddDefinitionScheduleUrl = '/api/scenario/schedule/add'; // 接口定义-定时同步-添加
// export const SwitchDefinitionScheduleUrl = '/api/scenario/schedule/switch'; // 接口定义-定时同步-开启关闭
// export const GetDefinitionScheduleUrl = '/api/scenario/schedule/get'; // 接口定义-定时同步-查询
// export const DeleteDefinitionScheduleUrl = '/api/scenario/schedule/delete'; // 接口定义-定时同步-删除
// export const DebugDefinitionUrl = '/api/scenario/debug'; // 接口定义-调试
