/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix'];
    AAlert: typeof import('@arco-design/web-vue')['Alert'];
    AAvatar: typeof import('@arco-design/web-vue')['Avatar'];
    ABadge: typeof import('@arco-design/web-vue')['Badge'];
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb'];
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem'];
    AButton: typeof import('@arco-design/web-vue')['Button'];
    ACard: typeof import('@arco-design/web-vue')['Card'];
    ACardMeta: typeof import('@arco-design/web-vue')['CardMeta'];
    ACol: typeof import('@arco-design/web-vue')['Col'];
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider'];
    ADivider: typeof import('@arco-design/web-vue')['Divider'];
    ADoption: typeof import('@arco-design/web-vue')['Doption'];
    ADrawer: typeof import('@arco-design/web-vue')['Drawer'];
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown'];
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber'];
    ALayout: typeof import('@arco-design/web-vue')['Layout'];
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent'];
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter'];
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider'];
    ALink: typeof import('@arco-design/web-vue')['Link'];
    AList: typeof import('@arco-design/web-vue')['List'];
    AListItem: typeof import('@arco-design/web-vue')['ListItem'];
    AListItemMeta: typeof import('@arco-design/web-vue')['ListItemMeta'];
    AMenu: typeof import('@arco-design/web-vue')['Menu'];
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem'];
    AModal: typeof import('@arco-design/web-vue')['Modal'];
    AOption: typeof import('@arco-design/web-vue')['Option'];
    APagination: typeof import('@arco-design/web-vue')['Pagination'];
    APopover: typeof import('@arco-design/web-vue')['Popover'];
    AResult: typeof import('@arco-design/web-vue')['Result'];
    ARow: typeof import('@arco-design/web-vue')['Row'];
    ASelect: typeof import('@arco-design/web-vue')['Select'];
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton'];
    ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine'];
    ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape'];
    ASpace: typeof import('@arco-design/web-vue')['Space'];
    ASpin: typeof import('@arco-design/web-vue')['Spin'];
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu'];
    ASwitch: typeof import('@arco-design/web-vue')['Switch'];
    ATabPane: typeof import('@arco-design/web-vue')['TabPane'];
    ATabs: typeof import('@arco-design/web-vue')['Tabs'];
    ATag: typeof import('@arco-design/web-vue')['Tag'];
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip'];
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph'];
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
