export const ELEMENTS = new Map([
  ['ALL', ["Plugin","scenario", "HTTPSamplerProxy", "DubboSampler", "JDBCSampler", "TCPSampler", "OT_IMPORT", "IfController", "TransactionController", "LoopController", "ConstantTimer", "JSR223Processor", "CustomizeReq"]],
  ['scenario', ["HTTPSamplerProxy", "DubboSampler", "JDBCSampler", "TCPSampler", "CASE", "OT_IMPORT", "IfController", "ConstantTimer", "JSR223Processor", "CustomizeReq"]],
  ['HTTPSamplerProxy', ["ConstantTimer", "JSR223PreProcessor", "JSR223PostProcessor", 'JDBCPreProcessor', 'JDBCPostProcessor', "Assertions", "Extract"]],
  ['DubboSampler', ["ConstantTimer", "JSR223PreProcessor", "JSR223PostProcessor", 'JDBCPreProcessor', 'JDBCPostProcessor', "Assertions", "Extract"]],
  ['JDBCSampler', ["ConstantTimer", "JSR223PreProcessor", "JSR223PostProcessor", 'JDBCPreProcessor', 'JDBCPostProcessor', "Assertions", "Extract"]],
  ['TCPSampler', ["ConstantTimer", "JSR223PreProcessor", "JSR223PostProcessor", 'JDBCPreProcessor', 'JDBCPostProcessor', "Assertions", "Extract"]],
  ['OT_IMPORT', ["ConstantTimer", "JSR223PreProcessor", "JSR223PostProcessor", 'JDBCPreProcessor', 'JDBCPostProcessor', "Assertions", "Extract"]],
  ['IfController', ["IfController", "LoopController", "TransactionController", "scenario", "HTTPSamplerProxy", "DubboSampler", "JDBCSampler", "TCPSampler", "OT_IMPORT", "ConstantTimer", "JSR223Processor", "JSR223PreProcessor", "JSR223PostProcessor", 'JDBCPreProcessor', 'JDBCPostProcessor', "Assertions", "Extract", "CustomizeReq"]],
  ['TransactionController', ["TransactionController", "scenario", "HTTPSamplerProxy", "DubboSampler", "JDBCSampler", "TCPSampler", "OT_IMPORT", "ConstantTimer", "JSR223Processor", "JSR223PreProcessor", "JSR223PostProcessor", 'JDBCPreProcessor', 'JDBCPostProcessor', "Assertions", "Extract", "CustomizeReq"]],
  ['LoopController', ["IfController", "TransactionController", "scenario", "HTTPSamplerProxy", "DubboSampler", "JDBCSampler", "TCPSampler", "OT_IMPORT", "ConstantTimer", "JSR223Processor", "JSR223PreProcessor", "JSR223PostProcessor", 'JDBCPreProcessor', 'JDBCPostProcessor', "Assertions", "Extract", "CustomizeReq"]],
  ['ConstantTimer', []],
  ['JSR223Processor', ["ConstantTimer", "JSR223PreProcessor", "JSR223PostProcessor", "Assertions", "Extract"]],
  ['JSR223PreProcessor', []],
  ['JSR223PostProcessor', []],
  ['JDBCPreProcessor', []],
  ['JDBCPostProcessor', []],
  ['Assertions', []],
  ['Extract', []],
  ['JmeterElement', []],
  ['CustomizeReq', ["ConstantTimer", "JSR223PreProcessor", "JSR223PostProcessor", "JDBCPostProcessor", "JDBCPreProcessor", "Assertions", "Extract"]],
  ['MaxSamplerProxy', ["JSR223PreProcessor", "JSR223PostProcessor", "JDBCPreProcessor", "JDBCPostProcessor", "Assertions", "Extract"]],
  ['AllSamplerProxy', ["HTTPSamplerProxy", "DubboSampler", "JDBCSampler", "TCPSampler"]],
  ['AllCanExecType', ["HTTPSamplerProxy", "DubboSampler", "JDBCSampler", "TCPSampler", "JSR223Processor"]]
])

export const ELEMENT_TYPE = {
  scenario: "scenario",
  HTTPSamplerProxy: "HTTPSamplerProxy",
  OT_IMPORT: "OT_IMPORT",
  IfController: "IfController",
  TransactionController: "TransactionController",
  ConstantTimer: "ConstantTimer",
  JSR223Processor: "JSR223Processor",
  JSR223PreProcessor: "JSR223PreProcessor",
  JSR223PostProcessor: "JSR223PostProcessor",
  JDBCPostProcessor: "JDBCPostProcessor",
  JDBCPreProcessor: "JDBCPreProcessor",
  Assertions: "Assertions",
  Extract: "Extract",
  CustomizeReq: "CustomizeReq",
  LoopController: "LoopController",
  Plugin: "Plugin"
}

export const TYPE_TO_C = new Map([
  ['scenario', "io.metersphere.api.dto.definition.request.MsScenario"],
  ['HTTPSamplerProxy', "io.metersphere.api.dto.definition.request.sampler.MsHTTPSamplerProxy"],
  ['DubboSampler', "io.metersphere.api.dto.definition.request.sampler.MsDubboSampler"],
  ['JDBCSampler', "io.metersphere.api.dto.definition.request.sampler.MsJDBCSampler"],
  ['TCPSampler', "io.metersphere.api.dto.definition.request.sampler.MsTCPSampler"],
  ['IfController', "io.metersphere.api.dto.definition.request.controller.MsIfController"],
  ['TransactionController', "io.metersphere.api.dto.definition.request.controller.MsTransactionController"],
  ['LoopController', "io.metersphere.api.dto.definition.request.controller.MsLoopController"],
  ['ConstantTimer', "io.metersphere.api.dto.definition.request.timer.MsConstantTimer"],
  ['JSR223Processor', "io.metersphere.api.dto.definition.request.processors.MsJSR223Processor"],
  ['JSR223PreProcessor', "io.metersphere.api.dto.definition.request.processors.pre.MsJSR223PreProcessor"],
  ['JSR223PostProcessor', "io.metersphere.api.dto.definition.request.processors.post.MsJSR223PostProcessor"],
  ['JDBCPreProcessor', "io.metersphere.api.dto.definition.request.processors.pre.MsJDBCPreProcessor"],
  ['JDBCPostProcessor', "io.metersphere.api.dto.definition.request.processors.post.MsJDBCPostProcessor"],
  ['Assertions', "io.metersphere.api.dto.definition.request.assertions.MsAssertions"],
  ['Extract', "io.metersphere.api.dto.definition.request.extract.MsExtract"],
  ['JmeterElement', "io.metersphere.api.dto.definition.request.unknown.MsJmeterElement"],
  ['TestPlan', "io.metersphere.api.dto.definition.request.MsTestPlan"],
  ['ThreadGroup', "io.metersphere.api.dto.definition.request.MsThreadGroup"],
  ['DNSCacheManager', "io.metersphere.api.dto.definition.request.dns.MsDNSCacheManager"],
  ['DebugSampler', "io.metersphere.api.dto.definition.request.sampler.MsDebugSampler"],

])
