package io.metersphere.commons.enums;

public enum MockParamConditionEnums {
    VALUE_EQUALS, VALUE_NOT_EQUALS, VALUE_CONTAINS, LENGTH_EQUALS, LENGTH_NOT_EQUALS, LENGTH_LARGE_THAN, LENGTH_SHOT_THAN, REGULAR_MATCH
}
