package io.metersphere.sdk.constants;

/**
 * @author jianxing
 */
public class PermissionConstants {

    /*------ start: SYSTEM_USER_ROLE ------*/
    public static final String SYSTEM_USER_ROLE_READ = "SYSTEM_USER_ROLE:READ";
    public static final String SYSTEM_USER_ROLE_ADD = "SYSTEM_USER_ROLE:READ+ADD";
    public static final String SYSTEM_USER_ROLE_UPDATE = "SYSTEM_USER_ROLE:READ+UPDATE";
    public static final String SYSTEM_USER_ROLE_DELETE = "SYSTEM_USER_ROLE:READ+DELETE";
    /*------ end: SYSTEM_USER_ROLE ------*/

    /*------ start: SYSTEM_ORGANIZATION_PROJECT ------*/
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ = "SYSTEM_ORGANIZATION_PROJECT:READ";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_ADD = "SYSTEM_ORGANIZATION_PROJECT:READ+ADD";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_UPDATE = "SYSTEM_ORGANIZATION_PROJECT:READ+UPDATE";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_DELETE = "SYSTEM_ORGANIZATION_PROJECT:READ+DELETE";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_RECOVER = "SYSTEM_ORGANIZATION_PROJECT:READ+RECOVER";
    public static final String SYSTEM_ORGANIZATION_PROJECT_MEMBER_ADD = "SYSTEM_ORGANIZATION_PROJECT_MEMBER:ADD";
    public static final String SYSTEM_ORGANIZATION_PROJECT_MEMBER_DELETE = "SYSTEM_ORGANIZATION_PROJECT_MEMBER:DELETE";
    /*------ end: SYSTEM_ORGANIZATION_PROJECT ------*/

    /*------ start: ORGANIZATION_USER_ROLE ------*/
    public static final String ORGANIZATION_USER_ROLE_READ = "ORGANIZATION_USER_ROLE:READ";
    public static final String ORGANIZATION_USER_ROLE_READ_ADD = "ORGANIZATION_USER_ROLE:READ+ADD";
    public static final String ORGANIZATION_USER_ROLE_READ_UPDATE = "ORGANIZATION_USER_ROLE:READ+UPDATE";
    public static final String ORGANIZATION_USER_ROLE_READ_DELETE = "ORGANIZATION_USER_ROLE:READ+DELETE";
    /*------ end: ORGANIZATION_USER_ROLE ------*/

    /*------ start: ORGANIZATION_MEMBER ------*/
    public static final String ORGANIZATION_MEMBER_READ = "ORGANIZATION_MEMBER:READ";
    public static final String ORGANIZATION_MEMBER_ADD = "ORGANIZATION_MEMBER:READ+ADD";
    public static final String ORGANIZATION_MEMBER_UPDATE = "ORGANIZATION_MEMBER:READ+UPDATE";
    public static final String ORGANIZATION_MEMBER_DELETE = "ORGANIZATION_MEMBER:READ+DELETE";
    /*------ end: ORGANIZATION_MEMBER ------*/

    /*------ start: ORGANIZATION_PROJECT ------*/
    public static final String ORGANIZATION_PROJECT_READ = "ORGANIZATION_PROJECT:READ";
    public static final String ORGANIZATION_PROJECT_READ_ADD = "ORGANIZATION_PROJECT:READ+ADD";
    public static final String ORGANIZATION_PROJECT_READ_UPDATE = "ORGANIZATION_PROJECT:READ+UPDATE";
    public static final String ORGANIZATION_PROJECT_READ_DELETE = "ORGANIZATION_PROJECT:READ+DELETE";
    public static final String ORGANIZATION_PROJECT_READ_RECOVER = "ORGANIZATION_PROJECT:READ+RECOVER";
    public static final String ORGANIZATION_PROJECT_MEMBER_ADD = "ORGANIZATION_PROJECT_MEMBER:ADD";
    public static final String ORGANIZATION_PROJECT_MEMBER_DELETE = "ORGANIZATION_PROJECT_MEMBER:DELETE";

    /*------ end: ORGANIZATION_PROJECT ------*/

    /*------ start: SYSTEM_PLUGIN ------*/
    public static final String SYSTEM_PLUGIN_READ = "SYSTEM_PLUGIN:READ";
    public static final String SYSTEM_PLUGIN_ADD = "SYSTEM_PLUGIN:READ+ADD";
    public static final String SYSTEM_PLUGIN_UPDATE = "SYSTEM_PLUGIN:READ+UPDATE";
    public static final String SYSTEM_PLUGIN_DELETE = "SYSTEM_PLUGIN:READ+DELETE";
    /*------ end: SYSTEM_PLUGIN ------*/

    /*------ start: SYSTEM_SERVICE_INTEGRATION ------*/
    public static final String SYSTEM_SERVICE_INTEGRATION_READ = "SYSTEM_SERVICE_INTEGRATION:READ";
    public static final String SYSTEM_SERVICE_INTEGRATION_ADD = "SYSTEM_SERVICE_INTEGRATION:READ+ADD";
    public static final String SYSTEM_SERVICE_INTEGRATION_UPDATE = "SYSTEM_SERVICE_INTEGRATION:READ+UPDATE";
    public static final String SYSTEM_SERVICE_INTEGRATION_DELETE = "SYSTEM_SERVICE_INTEGRATION:READ+DELETE";
    /*------ end: SYSTEM_SERVICE_INTEGRATION ------*/

    /*------ start: SYSTEM_SERVICE_INTEGRATION ------*/
    public static final String SYSTEM_USER_READ = "SYSTEM_USER:READ";
    public static final String SYSTEM_USER_ADD = "SYSTEM_USER:READ+ADD";
    public static final String SYSTEM_USER_IMPORT = "SYSTEM_USER:READ+IMPORT";
    public static final String SYSTEM_USER_UPDATE = "SYSTEM_USER:READ+UPDATE";
    public static final String SYSTEM_USER_DELETE = "SYSTEM_USER:READ+DELETE";
    /*------ end: SYSTEM_SERVICE_INTEGRATION ------*/

    public static final String SYSTEM_TEST_RESOURCE_POOL_READ = "SYSTEM_TEST_RESOURCE_POOL:READ";
    public static final String SYSTEM_TEST_RESOURCE_POOL_READ_ADD = "SYSTEM_TEST_RESOURCE_POOL:READ+ADD";
    public static final String SYSTEM_TEST_RESOURCE_POOL_READ_UPDATE = "SYSTEM_TEST_RESOURCE_POOL:READ+UPDATE";
    public static final String SYSTEM_TEST_RESOURCE_POOL_READ_DELETE = "SYSTEM_TEST_RESOURCE_POOL:READ+DELETE";


    /*------ start: SYSTEM_PARAMETER_SETTING ------*/
    public static final String SYSTEM_PARAMETER_SETTING_BASE_READ = "SYSTEM_PARAMETER_SETTING_BASE:READ";
    public static final String SYSTEM_PARAMETER_SETTING_BASE_READ_UPDATE = "SYSTEM_PARAMETER_SETTING_BASE:READ+UPDATE";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ = "SYSTEM_PARAMETER_SETTING_AUTH:READ";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ_ADD = "SYSTEM_PARAMETER_SETTING_AUTH:READ+ADD";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ_UPDATE = "SYSTEM_PARAMETER_SETTING_AUTH:READ+UPDATE";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ_DELETE = "SYSTEM_PARAMETER_SETTING_AUTH:READ+DELETE";
    public static final String SYSTEM_PARAMETER_SETTING_DISPLAY_READ = "SYSTEM_PARAMETER_SETTING_DISPLAY:READ";
    public static final String SYSTEM_PARAMETER_SETTING_DISPLAY_READ_UPDATE = "SYSTEM_PARAMETER_SETTING_DISPLAY:READ+UPDATE";

    /*------ end: SYSTEM_PARAMETER_SETTING ------*/

    /*------ start: ORGANIZATION_CUSTOM_FIELD ------*/
    public static final String ORGANIZATION_CUSTOM_FIELD_READ = "ORGANIZATION_CUSTOM_FIELD:READ";
    public static final String ORGANIZATION_CUSTOM_FIELD_ADD = "ORGANIZATION_CUSTOM_FIELD:READ+ADD";
    public static final String ORGANIZATION_CUSTOM_FIELD_UPDATE = "ORGANIZATION_CUSTOM_FIELD:READ+UPDATE";
    public static final String ORGANIZATION_CUSTOM_FIELD_DELETE = "ORGANIZATION_CUSTOM_FIELD:READ+DELETE";
    /*------ end: ORGANIZATION_CUSTOM_FIELD ------*/

    /*------ start: ORGANIZATION_TEMPLATE ------*/
    public static final String ORGANIZATION_TEMPLATE_READ = "ORGANIZATION_TEMPLATE:READ";
    public static final String ORGANIZATION_TEMPLATE_ADD = "ORGANIZATION_TEMPLATE:READ+ADD";
    public static final String ORGANIZATION_TEMPLATE_UPDATE = "ORGANIZATION_TEMPLATE:READ+UPDATE";
    public static final String ORGANIZATION_TEMPLATE_DELETE = "ORGANIZATION_TEMPLATE:READ+DELETE";
    /*------ end: ORGANIZATION_TEMPLATE ------*/

    /**
     * 项目成员权限
     */
    /*------ start: PROJECT_USER ------*/
    public static final String PROJECT_USER_READ = "PROJECT_USER:READ";
    public static final String PROJECT_USER_ADD = "PROJECT_USER:READ+ADD";
    public static final String PROJECT_USER_UPDATE = "PROJECT_USER:READ+UPDATE";
    public static final String PROJECT_USER_DELETE = "PROJECT_USER:READ+DELETE";
    /*------ end: PROJECT_MEMBER ------*/

    /**
     * 项目用户组
     */
    /*------ start: PROJECT_GROUP ------*/
    public static final String PROJECT_GROUP_READ = "PROJECT_GROUP:READ";
    public static final String PROJECT_GROUP_ADD = "PROJECT_GROUP:READ+ADD";
    public static final String PROJECT_GROUP_UPDATE = "PROJECT_GROUP:READ+UPDATE";
    public static final String PROJECT_GROUP_DELETE = "PROJECT_GROUP:READ+DELETE";
    /*------ end: PROJECT_USER_ROLE ------*/

    public static final String SYSTEM_AUTH_READ = "SYSTEM_AUTH:READ";
    public static final String SYSTEM_AUTH_READ_UPDATE = "SYSTEM_AUTH:READ+UPDATE";

    public static final String SYSTEM_LOG_READ = "SYSTEM_LOG:READ";

    public static final String ORGANIZATION_LOG_READ = "ORGANIZATION_LOG:READ";
    public static final String PROJECT_LOG_READ = "PROJECT_LOG:READ";

    public static final String PROJECT_USER_READ_ADD = "PROJECT_USER:READ+ADD";
    public static final String PROJECT_USER_READ_DELETE = "PROJECT_USER:READ+DELETE";

    public static final String PROJECT_API_DEFINITION_READ_ADD_API = "PROJECT_API_DEFINITION:READ+ADD_API";
    public static final String PROJECT_API_REPORT_READ_DELETE = "PROJECT_API_REPORT:READ+DELETE";

    public static final String PROJECT_MESSAGE_READ = "PROJECT_MESSAGE:READ";
    public static final String PROJECT_MESSAGE_READ_UPDATE = "PROJECT_MESSAGE:READ+UPDATE";
    public static final String PROJECT_MESSAGE_READ_ADD = "PROJECT_MESSAGE:READ+ADD";
    public static final String PROJECT_MESSAGE_READ_DELETE = "PROJECT_MESSAGE:READ+DELETE";

    /*------ start: PROJECT_APPLICATION ------*/
    public static final String PROJECT_APPLICATION_TEST_PLAN_READ = "PROJECT_APPLICATION_TEST_PLAN:READ";
    public static final String PROJECT_APPLICATION_TEST_PLAN_UPDATE = "PROJECT_APPLICATION_TEST_PLAN:UPDATE";
    public static final String PROJECT_APPLICATION_UI_READ = "PROJECT_APPLICATION_UI:READ";
    public static final String PROJECT_APPLICATION_UI_UPDATE = "PROJECT_APPLICATION_UI:UPDATE";
    public static final String PROJECT_APPLICATION_PERFORMANCE_TEST_READ = "PROJECT_APPLICATION_PERFORMANCE_TEST:READ";
    public static final String PROJECT_APPLICATION_PERFORMANCE_TEST_UPDATE = "PROJECT_APPLICATION_PERFORMANCE_TEST:UPDATE";
    public static final String PROJECT_APPLICATION_API_READ = "PROJECT_APPLICATION_API:READ";
    public static final String PROJECT_APPLICATION_API_UPDATE = "PROJECT_APPLICATION_API:UPDATE";
    public static final String PROJECT_APPLICATION_CASE_READ = "PROJECT_APPLICATION_CASE:READ";
    public static final String PROJECT_APPLICATION_CASE_UPDATE = "PROJECT_APPLICATION_CASE:UPDATE";
    /*------ end: PROJECT_APPLICATION ------*/
    public static final String PROJECT_BASE_INFO_READ = "PROJECT_BASE_INFO:READ";

    /**
     * 项目环境权限
     */
    /*------ start: PROJECT_ENVIRONMENT ------*/
    public static final String PROJECT_ENVIRONMENT_READ = "PROJECT_ENVIRONMENT:READ";
    public static final String PROJECT_ENVIRONMENT_READ_ADD = "PROJECT_ENVIRONMENT:READ+ADD";
    public static final String PROJECT_ENVIRONMENT_READ_UPDATE = "PROJECT_ENVIRONMENT:READ+UPDATE";
    public static final String PROJECT_ENVIRONMENT_READ_DELETE = "PROJECT_ENVIRONMENT:READ+DELETE";
    public static final String PROJECT_ENVIRONMENT_READ_IMPORT = "PROJECT_ENVIRONMENT:READ+IMPORT";
    public static final String PROJECT_ENVIRONMENT_READ_EXPORT = "PROJECT_ENVIRONMENT:READ+EXPORT";
    /*------ end: PROJECT_ENVIRONMENT ------*/


}
