package io.metersphere.sdk.constants;

/**
 * @author jianxing
 */
public class PermissionConstants {

    /*------ start: SYSTEM_USER_ROLE ------*/
    public static final String SYSTEM_USER_ROLE_READ = "SYSTEM_USER_ROLE:READ";
    public static final String SYSTEM_USER_ROLE_ADD = "SYSTEM_USER_ROLE:READ+ADD";
    public static final String SYSTEM_USER_ROLE_UPDATE = "SYSTEM_USER_ROLE:READ+UPDATE";
    public static final String SYSTEM_USER_ROLE_DELETE = "SYSTEM_USER_ROLE:READ+DELETE";
    /*------ end: SYSTEM_USER_ROLE ------*/

    /*------ start: SYSTEM_ORGANIZATION_PROJECT ------*/
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ = "SYSTEM_ORGANIZATION_PROJECT:READ";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_ADD = "SYSTEM_ORGANIZATION_PROJECT:READ+ADD";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_UPDATE = "SYSTEM_ORGANIZATION_PROJECT:READ+UPDATE";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_DELETE = "SYSTEM_ORGANIZATION_PROJECT:READ+DELETE";
    public static final String SYSTEM_ORGANIZATION_PROJECT_READ_RECOVER = "SYSTEM_ORGANIZATION_PROJECT:READ+RECOVER";
    public static final String SYSTEM_ORGANIZATION_PROJECT_MEMBER_ADD = "SYSTEM_ORGANIZATION_PROJECT_MEMBER:ADD";
    public static final String SYSTEM_ORGANIZATION_PROJECT_MEMBER_DELETE = "SYSTEM_ORGANIZATION_PROJECT_MEMBER:DELETE";
    /*------ end: SYSTEM_ORGANIZATION_PROJECT ------*/

    /*------ start: ORGANIZATION_USER_ROLE ------*/
    public static final String ORGANIZATION_USER_ROLE_READ = "ORGANIZATION_USER_ROLE:READ";
    public static final String ORGANIZATION_USER_ROLE_READ_ADD = "ORGANIZATION_USER_ROLE:READ+ADD";
    public static final String ORGANIZATION_USER_ROLE_READ_UPDATE = "ORGANIZATION_USER_ROLE:READ+UPDATE";
    public static final String ORGANIZATION_USER_ROLE_READ_DELETE = "ORGANIZATION_USER_ROLE:READ+DELETE";
    /*------ end: ORGANIZATION_USER_ROLE ------*/

    /*------ start: ORGANIZATION_MEMBER ------*/
    public static final String ORGANIZATION_MEMBER_READ = "ORGANIZATION_MEMBER:READ";
    public static final String ORGANIZATION_MEMBER_ADD = "ORGANIZATION_MEMBER:READ+ADD";
    public static final String ORGANIZATION_MEMBER_UPDATE = "ORGANIZATION_MEMBER:READ+UPDATE";
    public static final String ORGANIZATION_MEMBER_DELETE = "ORGANIZATION_MEMBER:READ+DELETE";
    /*------ end: ORGANIZATION_MEMBER ------*/

    /*------ start: ORGANIZATION_PROJECT ------*/
    public static final String ORGANIZATION_PROJECT_READ = "ORGANIZATION_PROJECT:READ";
    public static final String ORGANIZATION_PROJECT_READ_ADD = "ORGANIZATION_PROJECT:READ+ADD";
    public static final String ORGANIZATION_PROJECT_READ_UPDATE = "ORGANIZATION_PROJECT:READ+UPDATE";
    public static final String ORGANIZATION_PROJECT_READ_DELETE = "ORGANIZATION_PROJECT:READ+DELETE";
    public static final String ORGANIZATION_PROJECT_READ_RECOVER = "ORGANIZATION_PROJECT:READ+RECOVER";
    public static final String ORGANIZATION_PROJECT_MEMBER_ADD = "ORGANIZATION_PROJECT_MEMBER:ADD";
    public static final String ORGANIZATION_PROJECT_MEMBER_DELETE = "ORGANIZATION_PROJECT_MEMBER:DELETE";

    /*------ end: ORGANIZATION_PROJECT ------*/

    /*------ start: SYSTEM_PLUGIN ------*/
    public static final String SYSTEM_PLUGIN_READ = "SYSTEM_PLUGIN_READ:READ";
    public static final String SYSTEM_PLUGIN_ADD = "SYSTEM_PLUGIN_READ:READ+ADD";
    public static final String SYSTEM_PLUGIN_UPDATE = "SYSTEM_PLUGIN_READ:READ+UPDATE";
    public static final String SYSTEM_PLUGIN_DELETE = "SYSTEM_PLUGIN_READ:READ+DELETE";
    /*------ end: SYSTEM_PLUGIN ------*/

    /*------ start: SYSTEM_SERVICE_INTEGRATION ------*/
    public static final String SYSTEM_SERVICE_INTEGRATION_READ = "SYSTEM_SERVICE_INTEGRATION_READ:READ";
    public static final String SYSTEM_SERVICE_INTEGRATION_ADD = "SYSTEM_SERVICE_INTEGRATION_READ:READ+ADD";
    public static final String SYSTEM_SERVICE_INTEGRATION_UPDATE = "SYSTEM_SERVICE_INTEGRATION_READ:READ+UPDATE";
    public static final String SYSTEM_SERVICE_INTEGRATION_DELETE = "SYSTEM_SERVICE_INTEGRATION_READ:READ+DELETE";
    /*------ end: SYSTEM_SERVICE_INTEGRATION ------*/

    /*------ start: SYSTEM_SERVICE_INTEGRATION ------*/
    public static final String SYSTEM_USER_READ = "SYSTEM_USER:READ";
    public static final String SYSTEM_USER_ADD = "SYSTEM_USER:READ+ADD";
    public static final String SYSTEM_USER_IMPORT = "SYSTEM_USER:READ+IMPORT";
    public static final String SYSTEM_USER_UPDATE = "SYSTEM_USER:READ+UPDATE";
    public static final String SYSTEM_USER_DELETE = "SYSTEM_USER:READ+DELETE";
    /*------ end: SYSTEM_SERVICE_INTEGRATION ------*/

    public static final String SYSTEM_TEST_RESOURCE_POOL_READ = "SYSTEM_TEST_RESOURCE_POOL:READ";
    public static final String SYSTEM_TEST_RESOURCE_POOL_READ_ADD = "SYSTEM_TEST_RESOURCE_POOL:READ+ADD";
    public static final String SYSTEM_TEST_RESOURCE_POOL_READ_UPDATE = "SYSTEM_TEST_RESOURCE_POOL:READ+UPDATE";
    public static final String SYSTEM_TEST_RESOURCE_POOL_READ_DELETE = "SYSTEM_TEST_RESOURCE_POOL:READ+DELETE";


    /*------ start: SYSTEM_PARAMETER_SETTING ------*/
    public static final String SYSTEM_PARAMETER_SETTING_BASE_READ = "SYSTEM_PARAMETER_SETTING_BASE:READ";
    public static final String SYSTEM_PARAMETER_SETTING_BASE_READ_UPDATE = "SYSTEM_PARAMETER_SETTING_BASE:READ+UPDATE";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ = "SYSTEM_PARAMETER_SETTING_AUTH:READ";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ_ADD = "SYSTEM_PARAMETER_SETTING_AUTH:READ+ADD";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ_UPDATE = "SYSTEM_PARAMETER_SETTING_AUTH:READ+UPDATE";
    public static final String SYSTEM_PARAMETER_SETTING_AUTH_READ_DELETE = "SYSTEM_PARAMETER_SETTING_AUTH:READ+DELETE";

    /*------ end: SYSTEM_PARAMETER_SETTING ------*/

    /**
     * 项目成员权限
     */
    /*------ start: PROJECT_MEMBER ------*/
    public static final String PROJECT_MEMBER_READ = "PROJECT_MEMBER:READ";
    public static final String PROJECT_MEMBER_ADD = "PROJECT_MEMBER:READ+ADD";
    public static final String PROJECT_MEMBER_UPDATE = "PROJECT_MEMBER:READ+UPDATE";
    public static final String PROJECT_MEMBER_DELETE = "PROJECT_MEMBER:READ+DELETE";
    /*------ end: PROJECT_MEMBER ------*/

    public static final String SYSTEM_AUTH_READ = "SYSTEM_AUTH:READ";
    public static final String SYSTEM_AUTH_READ_UPDATE = "SYSTEM_AUTH:READ+UPDATE";

    public static final String SYSTEM_LOG_READ = "SYSTEM_LOG:READ";

    public static final String ORGANIZATION_LOG_READ = "ORGANIZATION_LOG:READ";

    public static final String PROJECT_USER_READ_ADD = "PROJECT_USER:READ+ADD";
    public static final String PROJECT_USER_READ_DELETE = "PROJECT_USER:READ+DELETE";

    public static final String PROJECT_API_DEFINITION_READ_ADD_API = "PROJECT_API_DEFINITION:READ+ADD_API";
    public static final String PROJECT_API_REPORT_READ_DELETE = "PROJECT_API_REPORT:READ+DELETE";

    public static final String PROJECT_MESSAGE_READ = "PROJECT_MESSAGE:READ";
    public static final String PROJECT_MESSAGE_READ_UPDATE = "PROJECT_MESSAGE:READ+UPDATE";
    public static final String PROJECT_MESSAGE_READ_ADD = "PROJECT_MESSAGE:READ+ADD";
    public static final String PROJECT_MESSAGE_READ_DELETE = "PROJECT_MESSAGE:READ+DELETE";

    public static final String PROJECT_APPLICATION_TEST_PLAN_READ = "PROJECT_APPLICATION_TEST_PLAN:READ";
    public static final String PROJECT_APPLICATION_TEST_PLAN_UPDATE = "PROJECT_APPLICATION_TEST_PLAN:UPDATE";
}
