export const UploadFileUrl = '/project/file/upload'; // 上传文件
export const UpdateFileUrl = '/project/file/update'; // 更新文件
export const ReuploadFileUrl = '/project/file/re-upload'; // 重新上传文件
export const FilePageUrl = '/project/file/page'; // 分页查询文件列表
export const DeleteFileUrl = '/project/file/delete'; // 删除文件
export const DownloadFileUrl = '/project/file/download'; // 下载文件
export const BatchDownloadFileUrl = '/project/file/batch-download'; // 批量下载文件
export const UpdateModuleUrl = '/project/file-module/update'; // 更新模块
export const MoveModuleUrl = '/project/file-module/move'; // 移动模块
export const AddModuleUrl = '/project/file-module/add'; // 添加模块
export const GetModuleUrl = '/project/file-module/tree'; // 查找模块
export const DeleteModuleUrl = '/project/file-module/delete'; // 删除模块
export const GetModuleCountUrl = '/project/file/module/count'; // 模块统计文件数量
export const OriginImgUrl = '/file/preview/original'; // 预览图片文件接口-原图
export const CompressImgUrl = '/file/preview/compressed'; // 预览图片文件接口-缩略图
export const GetFileTypesUrl = '/project/file/type'; // 获取模块文件类型集合
export const GetFileDetailUrl = '/project/file/get'; // 查看文件详情
export const ToggleJarFileUrl = '/project/file/jar-file-status'; // jar 文件启用禁用
export const BatchMoveFileUrl = '/project/file/batch-move'; // jar 文件启用禁用
export const GetRepositoryFileUrl = '/project/file/repository/list'; // 存储库列表
export const GetRepositoryFileTypesUrl = '/project/file/repository/file-type'; // 存储库文件类型列表
export const UpdateRepositoryUrl = '/project/file/repository/update-repository'; // 修改存储库信息
export const ConnectRepositoryUrl = '/project/file/repository/connect'; // 测试存储库连接
export const AddRepositoryUrl = '/project/file/repository/add-repository'; // 添加存储库
