package io.metersphere.commons.constants;

public enum OperLogConstants {
    CREATE, DELETE, DEBUG, UPDATE, REVIEW, COPY, EXECUTE, SHARE, GC, RESTORE,
    BATCH_DEL, BATCH_UPDATE, BATCH_ADD, BATCH_RESTORE, BATCH_GC,
    IMPORT, EXPORT,
    ASSOCIATE_CASE, ASSOCIATE_ISSUE, UN_ASSOCIATE_CASE,
    LOGIN, PERMISSION_UPDATE, CREATE_PRE_TEST, OTHER,
    MINDER_OPERATION,
    REQUEST
}
