package io.metersphere.commons.constants;

public enum ScheduleGroup {
    PERFORMANCE_TEST, API_SCENARIO_TEST, TEST_PLAN_TEST, SWAGGER_IMPORT, ISSUE_SYNC,
    SCHEDULE_SEND_REPORT, CLEAN_UP_REPORT, UI_SCENARIO_TEST
}
