on: pull_request

name: MeterSphere 通用 PR 处理

permissions:
  pull-requests: write

jobs:
  generic_handler:
    name: 为 PR 添加标签
    runs-on: ubuntu-latest
    steps:
      - name: Add labels
        uses: jumpserver/action-generic-handler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ github.base_ref }}
