on:
  push:
    branches:
      - v3.*
    paths:
      - "backend/**"
      - "pom.xml"
  pull_request:
    branches:
      - v3.*
    paths:
      - "backend/**"
      - "pom.xml"

name: MeterSphere 覆盖率统计

permissions:
  pull-requests: write

jobs:
  generic_handler:
    name: 覆盖率统计
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'maven'
          cache-dependency-path: '**/pom.xml' # optional
          check-latest: true
      - name: Build with Maven - other
        run: mvn -B package -DskipAntRunForJenkins --file pom.xml -pl '!frontend'
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
