on:
  push:
    branches:
      - 'pr@**'
      - 'repr@**'

name: MeterSphere

jobs:
  generic_handler:
    name: 自动创建 PR
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: jumpserver/action-generic-handler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
