on:
  push:
    branches:
      - v3.*
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - v3.*
    paths:
      - "frontend/**"

name: MeterSphere 前端代码校验

permissions:
  pull-requests: write

jobs:
  generic_handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
          cache: 'maven'
          cache-dependency-path: '**/pom.xml' # optional
          check-latest: true
      - name: Build with Maven - only frontend
        run: mvn -T 1C -B package --file pom.xml -pl frontend
